
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: docker compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-api-feed hieudoantan/udagram-api-feed:v1
    - run: docker tag udagram-api-user hieudoantan/udagram-api-user:v1
    - run: docker tag udagram-frontend:local hieudoantan/udagram-frontend:v2
    - run: docker tag reverseproxy hieudoantan/udagram-reverseproxy:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push hieudoantan/udagram-api-feed:v1
    - run: docker push hieudoantan/udagram-api-user:v1
    - run: docker push hieudoantan/udagram-frontend:v2
    - run: docker push hieudoantan/udagram-reverseproxy:v1

